name: Build Opera Proxy for MT7621

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib git libncurses-dev libssl-dev \
          unzip zlib1g-dev file wget python3 python3-venv

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/24.10.2/targets/ramips/mt7621/openwrt-sdk-24.10.2-ramips-mt7621_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        tar --use-compress-program=unzstd -xf openwrt-sdk-24.10.2-ramips-mt7621_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        SDK_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-24.10.2-*" | head -n1)
        mv "$SDK_DIR" sdk

    - name: Clone opera-proxy upstream
      run: |
        git clone https://github.com/Snawoot/opera-proxy.git sdk/package/opera-proxy

    - name: Inject OpenWrt metadata
      run: |
        mkdir -p sdk/package/opera-proxy/files/etc/init.d
        mkdir -p sdk/package/opera-proxy/files/etc/config
        cp sdk/Makefile.sdk sdk/package/opera-proxy/Makefile
        # cp sdk/Config.in sdk/package/opera-proxy/Config.in
        cp sdk/files/etc/init.d/opera-proxy sdk/package/opera-proxy/files/etc/init.d/opera-proxy
        cp sdk/files/etc/config/opera-proxy sdk/package/opera-proxy/files/etc/config/opera-proxy
        chmod +x sdk/package/opera-proxy/files/etc/init.d/opera-proxy

    - name: Setup Python venv
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel

    - name: Enable opera-proxy package
      run: echo "CONFIG_PACKAGE_opera-proxy=y" >> sdk/.config

    - name: Build opera-proxy package
      run: |
        cd sdk
        make package/opera-proxy/compile V=s -j$(nproc)
        
    - name: Upload .ipk artifact
      uses: actions/upload-artifact@v4
      with:
        name: opera-proxy
        path: sdk/bin/packages/*/base/opera-proxy_*.ipk
